{{- if .Values.filebrowser.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-filebrowser" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: filebrowser
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.filebrowser.service.type }}
  selector: {{- include "common.labels.matchLabels" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: filebrowser
  ports:
    - name: http
      port: {{ .Values.filebrowser.service.port }}
      targetPort: {{ .Values.filebrowser.service.port }}
      {{- if and (eq .Values.filebrowser.service.type "NodePort") .Values.filebrowser.service.nodePort }}
      nodePort: {{ .Values.filebrowser.service.nodePort }}
      {{- end }}
{{- end }}
